version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Build Docker Image"
          command: docker build -t rfdesign . -f docker/Dockerfile

      - run:
          name : biolib push rfdesign
          command: biolib push damgaard22/rfdesign

                    

workflows:
  build:
    jobs:
      - build:
          context:
            - BIOLIB_TOKEN
