version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install pybiolib"
          command: |
            apk add --no-cache \
              py-pip3
            pip install --upgrade pip
            pip install pybiolib

      - run:
          name: "Build Docker Image"
          command: docker build -t rfdesign . -f docker/Dockerfile

      - run:
          name : biolib push rfdesign
          command: biolib push damgaard22/rfdesign

workflows:
  build:
    jobs:
      - build:
          context:
            - BIOLIB_TOKEN
