version: 2.1
jobs:
  build:
    docker:
      #- image: docker:17.05.0-ce-git
      - image: circleci/python

    steps:
#      - run:
#          name: "Install pybiolib"
#          command: |
#            apk update
#            apk add \
#              python3==3.11.0-r2
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Build Docker Image"
          command: docker build -t rfdesign . -f docker/Dockerfile
#
#      - run:
#          name : biolib push rfdesign
#          command: biolib push damgaard22/rfdesign

workflows:
  build:
    jobs:
      - build:
          context:
            - BIOLIB_TOKEN
