name: CI

on: push

env:
    BIOLIB_LOG: debug
    BIOLIB_PROJECT_URI: damgaard22/demo
    LOCAL_DOCKER_TAG: rfdesign:latest

jobs:
    build-and-publish:
        name: Build Docker image and publish if on main
        runs-on: ubuntu:20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 2
                    submodules: true

            -   name: Build docker image
                run: docker build -t $LOCAL_DOCKER_TAG . -f docker/Dockerfile

            -   name: Publish new version to BioLib if on main branch
                if: ${{ github.ref == 'refs/heads/main' }}
                run: biolib push $BIOLIB_PROJECT_URI
                env:
                    BIOLIB_TOKEN: ${{ secrets.BIOLIB_TOKEN }}
